flowchart LR
  S1[Leitor RFID] --> ESP[ESP32 Gateway]
  S2[Sensor Porta] --> ESP
  S3[Sensor Peso] --> ESP

  ESP --> BROKER[Broker MQTT]
  BROKER --> API[Backend FastAPI]
  BROKER --> DASH[Dashboard React]
  API --> DB[(PostgreSQL)]
  API --> ALT[Alertas]

  AWS[AWS IoT Core] -. futuro .-> BROKER
  AWS -. futuro .-> API
  AWS -. futuro .-> DASH
